### ISSUE TITLE
tracking potato usage

### ISSUE THREAD

**Issue by TheProducer835** [codingWithJimmy/LogToSplunk#6]
When a potato is used as a tool to break items it is listed as POTATO_ITEM under tool.item. When a baked potato is used as a tool it is listed as BAKED_POTATO

**Comment by PowerSchill** [comment]
In Spigot some items like potatoes have an entry for "POTATO" as well as "POTATO_ITEM". I don't know what the difference is and there are a bunch of items that do this. The easiest way might just be to drop "_ITEM" off when it appears at the end of the name so that ITEM_FRAME doesn't get affected. Will see if there is a consequence to doing that.
